server:
  port: 8080
  servlet:
    context-path: /duan

duanyuming:
  firstname: bbb
  lastname: bbb

user: ${duanyuming.firstname} ${duanyuming.lastname}
mysql:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/duan
  username: prod
  password: prod
